#ifndef __BOARD_RESOURCE_MAP_H
#define __BOARD_RESOURCE_MAP_H

#include "board_profile.h"

/*
 * Stable semantic resource map.
 * Future hardware changes should prefer updating these mappings first.
 */

#define BOARD_RES_STATE_LED_PORT          BOARD_STATE_LED_PORT
#define BOARD_RES_STATE_LED_PIN           BOARD_STATE_LED_PIN

/* 板上原A接口用PD1检测手柄插入；运行键另接固定引脚，不使用PD1。 */
#define BOARD_RES_HANDLE_PHYSICAL_A_SHORT_PORT   GPIOD
#define BOARD_RES_HANDLE_PHYSICAL_A_SHORT_PIN    GPIO_PIN_1

/* 板上原B接口用PD0检测手柄插入；运行键另接固定引脚，不使用PD0。 */
#define BOARD_RES_HANDLE_PHYSICAL_B_SHORT_PORT   GPIOD
#define BOARD_RES_HANDLE_PHYSICAL_B_SHORT_PIN    GPIO_PIN_0

#if (HANDLE_PHYSICAL_AB_SWAP_ENABLE == 1U)
/* A/B交叉接线时，屏幕A根据板上原B接口判断是否插入。 */
#define BOARD_RES_HANDLESCAN_A_SHORT_PORT BOARD_RES_HANDLE_PHYSICAL_B_SHORT_PORT
#define BOARD_RES_HANDLESCAN_A_SHORT_PIN  BOARD_RES_HANDLE_PHYSICAL_B_SHORT_PIN

/* A/B交叉接线时，屏幕B根据板上原A接口判断是否插入。 */
#define BOARD_RES_HANDLESCAN_B_SHORT_PORT BOARD_RES_HANDLE_PHYSICAL_A_SHORT_PORT
#define BOARD_RES_HANDLESCAN_B_SHORT_PIN  BOARD_RES_HANDLE_PHYSICAL_A_SHORT_PIN
#else
/* 关闭交换时恢复原接线：逻辑A对应物理A，逻辑B对应物理B。 */
#define BOARD_RES_HANDLESCAN_A_SHORT_PORT BOARD_RES_HANDLE_PHYSICAL_A_SHORT_PORT
#define BOARD_RES_HANDLESCAN_A_SHORT_PIN  BOARD_RES_HANDLE_PHYSICAL_A_SHORT_PIN
#define BOARD_RES_HANDLESCAN_B_SHORT_PORT BOARD_RES_HANDLE_PHYSICAL_B_SHORT_PORT
#define BOARD_RES_HANDLESCAN_B_SHORT_PIN  BOARD_RES_HANDLE_PHYSICAL_B_SHORT_PIN
#endif

/* A实体键固定复用UART10_RX/PE2，不再跟随旧手柄物理A/B交换配置。 */
#define BOARD_RES_HANDLE_RUN_KEY_A_PORT       BOARD_UART10_RX_PORT
#define BOARD_RES_HANDLE_RUN_KEY_A_PIN        BOARD_UART10_RX_PIN
#define BOARD_RES_HANDLE_RUN_KEY_A_UART_AF    BOARD_UART10_RX_AF

/* B实体键固定复用UART8_RX/PE0，不再兼容原PE12/PE13实体键映射。 */
#define BOARD_RES_HANDLE_RUN_KEY_B_PORT       BOARD_UART8_RX_PORT
#define BOARD_RES_HANDLE_RUN_KEY_B_PIN        BOARD_UART8_RX_PIN
#define BOARD_RES_HANDLE_RUN_KEY_B_UART_AF    BOARD_UART8_RX_AF

#define BOARD_RES_SOFT_IIC_SCL_PORT       BOARD_IIC_SCL_PORT
#define BOARD_RES_SOFT_IIC_SCL_PIN        BOARD_IIC_SCL_PIN
#define BOARD_RES_SOFT_IIC_SDA_PORT       BOARD_IIC_SDA_PORT
#define BOARD_RES_SOFT_IIC_SDA_PIN        BOARD_IIC_SDA_PIN

#define BOARD_RES_ONEWIRE_I_PORT          BOARD_ONEWIRE_I_PORT
#define BOARD_RES_ONEWIRE_I_PIN           BOARD_ONEWIRE_I_PIN
#define BOARD_RES_ONEWIRE_II_PORT         BOARD_ONEWIRE_II_PORT
#define BOARD_RES_ONEWIRE_II_PIN          BOARD_ONEWIRE_II_PIN

#endif /* __BOARD_RESOURCE_MAP_H */
